/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as RankingsRouteImport } from './routes/rankings'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as PersonSlugRouteImport } from './routes/person.$slug'
import { Route as ListSlugRouteImport } from './routes/list.$slug'
import { Route as CategorySlugRouteImport } from './routes/category.$slug'
import { Route as AdminRankingsRouteImport } from './routes/admin/rankings'
import { Route as AdminPeopleRouteImport } from './routes/admin/people'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminCategoriesRouteImport } from './routes/admin/categories'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingsRoute = RankingsRouteImport.update({
  id: '/rankings',
  path: '/rankings',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const PersonSlugRoute = PersonSlugRouteImport.update({
  id: '/person/$slug',
  path: '/person/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ListSlugRoute = ListSlugRouteImport.update({
  id: '/list/$slug',
  path: '/list/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRankingsRoute = AdminRankingsRouteImport.update({
  id: '/rankings',
  path: '/rankings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPeopleRoute = AdminPeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/categories': typeof CategoriesRoute
  '/rankings': typeof RankingsRoute
  '/search': typeof SearchRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/people': typeof AdminPeopleRoute
  '/admin/rankings': typeof AdminRankingsRoute
  '/category/$slug': typeof CategorySlugRoute
  '/list/$slug': typeof ListSlugRoute
  '/person/$slug': typeof PersonSlugRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/categories': typeof CategoriesRoute
  '/rankings': typeof RankingsRoute
  '/search': typeof SearchRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/people': typeof AdminPeopleRoute
  '/admin/rankings': typeof AdminRankingsRoute
  '/category/$slug': typeof CategorySlugRoute
  '/list/$slug': typeof ListSlugRoute
  '/person/$slug': typeof PersonSlugRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/categories': typeof CategoriesRoute
  '/rankings': typeof RankingsRoute
  '/search': typeof SearchRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/people': typeof AdminPeopleRoute
  '/admin/rankings': typeof AdminRankingsRoute
  '/category/$slug': typeof CategorySlugRoute
  '/list/$slug': typeof ListSlugRoute
  '/person/$slug': typeof PersonSlugRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/categories'
    | '/rankings'
    | '/search'
    | '/admin/categories'
    | '/admin/login'
    | '/admin/people'
    | '/admin/rankings'
    | '/category/$slug'
    | '/list/$slug'
    | '/person/$slug'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/categories'
    | '/rankings'
    | '/search'
    | '/admin/categories'
    | '/admin/login'
    | '/admin/people'
    | '/admin/rankings'
    | '/category/$slug'
    | '/list/$slug'
    | '/person/$slug'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/categories'
    | '/rankings'
    | '/search'
    | '/admin/categories'
    | '/admin/login'
    | '/admin/people'
    | '/admin/rankings'
    | '/category/$slug'
    | '/list/$slug'
    | '/person/$slug'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CategoriesRoute: typeof CategoriesRoute
  RankingsRoute: typeof RankingsRoute
  SearchRoute: typeof SearchRoute
  CategorySlugRoute: typeof CategorySlugRoute
  ListSlugRoute: typeof ListSlugRoute
  PersonSlugRoute: typeof PersonSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rankings': {
      id: '/rankings'
      path: '/rankings'
      fullPath: '/rankings'
      preLoaderRoute: typeof RankingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/person/$slug': {
      id: '/person/$slug'
      path: '/person/$slug'
      fullPath: '/person/$slug'
      preLoaderRoute: typeof PersonSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/list/$slug': {
      id: '/list/$slug'
      path: '/list/$slug'
      fullPath: '/list/$slug'
      preLoaderRoute: typeof ListSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/rankings': {
      id: '/admin/rankings'
      path: '/rankings'
      fullPath: '/admin/rankings'
      preLoaderRoute: typeof AdminRankingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/people': {
      id: '/admin/people'
      path: '/people'
      fullPath: '/admin/people'
      preLoaderRoute: typeof AdminPeopleRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminPeopleRoute: typeof AdminPeopleRoute
  AdminRankingsRoute: typeof AdminRankingsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminPeopleRoute: AdminPeopleRoute,
  AdminRankingsRoute: AdminRankingsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CategoriesRoute: CategoriesRoute,
  RankingsRoute: RankingsRoute,
  SearchRoute: SearchRoute,
  CategorySlugRoute: CategorySlugRoute,
  ListSlugRoute: ListSlugRoute,
  PersonSlugRoute: PersonSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
